### ISSUE TITLE
Server/network error on creating a new transaction

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/client-python#17]
Grakn version: 1.5 SNAPSHOT (c80b4d644aec10895171c2083ed0378b506b01f0)
Client version: 1.5 SNAPSHOT (http://repo.grakn.ai/repository/test-pypi-group/packages/grakn-client/1.5.0-252e5170fb3b13a0c08f7b9c5de59cb2b0a15ef4/grakn-client-1.5.0-252e5170fb3b13a0c08f7b9c5de59cb2b0a15ef4.tar.gz)

```python
import grakn

client = grakn.Grakn(uri="localhost:48555")
with client.session(keyspace="test") as session:
    with session.transaction(grakn.TxType.READ) as transaction:
        print(client, session, transaction)
```

## Expected outcome:
```
see the correct result of the print statement.
```

## Actual outcome
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 145, in send
    response = next(self._response_iterator)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 357, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "null. Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1551193247.463363000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"null. Please check server logs for the stack trace.","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    with session.transaction(grakn.TxType.READ) as transaction:
  File "/usr/local/lib/python3.7/site-packages/grakn/__init__.py", line 74, in transaction
    transaction_service = TransactionService(self.keyspace, tx_type, self.credentials, self._stub.transaction)
  File "/usr/local/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 39, in __init__
    self._communicator.send(open_req)
  File "/usr/local/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 149, in send
    raise ClientError("Server/network error: {0}\n\n generated from request: {1}".format(e, request))
grakn.exception.ClientError.ClientError: Server/network error: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "null. Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1551193247.463363000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"null. Please check server logs for the stack trace.","grpc_status":2}"
>

 generated from request: open_req {
  keyspace: "test"
}
```

```
2019-02-26 15:00:47,454 [grpc-default-executor-0] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
java.lang.NullPointerException: null
	at grakn.core.server.rpc.SessionService$TransactionListener.open(SessionService.java:271)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:191)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sorsaffari** [comment]
@vmax please take over this if you know what's caused it.

**Comment by vmax** [comment]
@sorsaffari the issue seems to be solved as of very latest [`grakn`](https://github.com/graknlabs/grakn/commit/2091602fbcca45823d2bc3d5062ce7cdb6b25b89) and [`client-python`](https://github.com/graknlabs/client-python/commit/6b56611aa98031191c0b02aadb30af5a203f8212)

Could you try it with these versions? (PyPI package: `pip install http://repo.grakn.ai/repository/test-pypi/packages/grakn-client/1.5.0-6b56611aa98031191c0b02aadb30af5a203f8212/grakn-client-1.5.0-6b56611aa98031191c0b02aadb30af5a203f8212.tar.gz`)
