### ISSUE TITLE
deploy-github fails because of python compatibility errors

### ISSUE THREAD

**Issue by lolski** [graknlabs/client-python#96]
There are two errors:

**ci:release-notes error** (https://circleci.com/gh/graknlabs/client-python/2166)
`ci:release-notes` would fail when pyenv global is set to 2.7.123.5.2. If we remove the pyenv call, it will work
```
pyenv global 2.7.12 3.5.2
pip install certifi
export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
bazel run @graknlabs_build_tools//ci:release-notes -- client-python $(cat VERSION) ./RELEASE_TEMPLATE.md

...
Traceback (most recent call last):
  File "/home/********/.cache/bazel/_bazel_********/a3bf690c4bacc2f8a31e33bc35f6090b/execroot/graknlabs_client_python/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci/release-notes.runfiles/graknlabs_build_tools/ci/release-notes.py", line 3, in <module>
    import github
  File "/home/********/.cache/bazel/_bazel_********/a3bf690c4bacc2f8a31e33bc35f6090b/execroot/graknlabs_client_python/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci/release-notes.runfiles/pypi__PyGithub_1_43_2/github/__init__.py", line 42, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/home/********/.cache/bazel/_bazel_********/a3bf690c4bacc2f8a31e33bc35f6090b/execroot/graknlabs_client_python/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci/release-notes.runfiles/pypi__PyGithub_1_43_2/github/MainClass.py", line 53, in <module>
    from httplib import HTTPSConnection
ImportError: No module named 'httplib'
```

**deploy-github error** (https://circleci.com/gh/graknlabs/client-python/2168)
`deploy-github` would fail if pyenv global is set to 2.7.123.5.2. I did not try testing invoking deploy-github without setting pyenv, so I didn't know if it'll work without the pyenv call.
```
pyenv global 2.7.12 3.5.2
export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
bazel run --define version=$(cat VERSION) //:deploy-github -- $CIRCLE_SHA1

...
Could not find pip-provided dependency: 'enum34'
ERROR: Skipping '//:deploy-github': no such target '//:deploy-github': target 'deploy-github' not declared in package '' defined by /home/********/client-python/BUILD
```

**Comment by lolski** [comment]
It is possible that the errors are caused by changes in this commit: https://github.com/graknlabs/client-python/commit/4c23b4946ebfc8ee5f54384a67fda8149dfe282d
